#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Santiago Garcia Mantinan (manty)

# This script should be /etc/init.d/reinstall
# For this to work, we should add to /etc/sysupgrade.conf without the "#":
#/etc/init.d/reinstall
#/etc/rc.d/S99reinstall
#/etc/reinstall.conf
# and before doing the sysupgrade to the new version we should run:
#/etc/init.d/reinstall enable
# The script will log the actions and result and disable itself.
# In reinstall.conf we specify the extra packages to install (one per line)
# or to disable if their name starts with a -

START=99
extra_command "check" "New installed packages since last reinstall"

REINSTALL_LOG=/root/reinstall.log
REINSTALL_STATUS=/root/reinstall.status

start() {
(
. /etc/profile
STATE="Something went wrong, manually run: /etc/init.d/reinstall start"
# Wait till we are stable
sleep 10
i=10;while [ $i -gt 0 ] && ! wget http://www.google.com -O /dev/null;do sleep 10;i=$((i-1));done
date
opkg update &&
  grep -v "^[[:space:]]*#" /etc/reinstall.conf |
    while read i;do
      if [ "$i" = "wpad" ];then
        echo "Getting ready to install full wpad by removing the lite ones"
        opkg remove wpad-basic wpad-basic-wolfssl wpad-basic-mbedtls
      fi
      if [ ! "${i%%-*}" ];then
        if [ ! "${i%%-/*}" ];then
          echo "Removing ${i#-}"
          rm -f "${i#-}"
        else
          echo "Disabling ${i#-}"
          /etc/init.d/"${i#-}" stop
          /etc/init.d/"${i#-}" disable
        fi
      else
        echo "Installing $i"
        opkg install "$i"
      fi
    done && STATE="Everything went Ok, reinstall has finished without errors." && opkg list-installed > "$REINSTALL_STATUS"
echo  "$STATE"
/etc/init.d/reinstall disable
reboot
) >"$REINSTALL_LOG" 2>&1 </dev/null &
}

check() {
if [ -f "$REINSTALL_STATUS" ]
then
  echo Checking for new installed packages since last reinstall...
  opkg list-installed|while read package rest;do if ! grep -q "^$package" "$REINSTALL_STATUS";then echo $package;fi;done
else
  echo "Missing $REINSTALL_STATUS, cannot check, sorry."
fi
}
