#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Santiago Garcia Mantinan (manty)

# This script should be /etc/init.d/reinstall
# For this to work, we should add to /etc/sysupgrade.conf without the "#":
#/etc/init.d/reinstall
#/etc/rc.d/S99reinstall
#/etc/reinstall.conf
# and before doing the sysupgrade to the new version we should run:
#/etc/init.d/reinstall enable
# The script will log the actions and result and disable itself.
# In reinstall.conf we specify the extra packages to install (one per line)
# or to disable if their name starts with a -

START=99
extra_command "check" "New installed packages since last reinstall"
extra_command "chen" "Check new packages and enable autostart"

REINSTALL_CONF=/etc/reinstall.conf
REINSTALL_LOG=/root/reinstall.log
if [ ! -e "$REINSTALL_CONF" ]
then
  REINSTALL_CONF="/dev/null"
fi

start() {
(
. /etc/profile
STATE="Something went wrong, manually run: /etc/init.d/reinstall start"
# Wait till we are stable
sleep 10
wait=10;while [ $wait -gt 0 ] && ! wget http://www.google.com -O /dev/null;do sleep 10;wait=$((wait-1));done
date
opkg update &&
  grep -v "^[[:space:]]*#" "$REINSTALL_CONF" |
    while read package;do
      if [ "$package" = "wpad" ];then
        echo "Getting ready to install full wpad by removing the lite ones"
        opkg remove wpad-basic wpad-basic-wolfssl wpad-basic-mbedtls
      fi
      if [ ! "${package%%-*}" ];then
        if [ ! "${package%%-/*}" ];then
          echo "Removing ${package#-}"
          rm -f "${package#-}"
        else
          echo "Disabling ${package#-}"
          /etc/init.d/"${package#-}" stop
          /etc/init.d/"${package#-}" disable
        fi
      else
        echo "Installing $package"
        opkg install "$package"
      fi
    done && STATE="Everything went Ok, reinstall has finished without errors."
echo  "$STATE"
/etc/init.d/reinstall disable
reboot
) >"$REINSTALL_LOG" 2>&1 </dev/null &
}

check() {
echo Checking for new installed packages since last reinstall...
opkg list-installed|while read package rest;do if opkg status "$package"|grep -q "Status: install user installed";then echo "$package";fi;done | while read package rest;do if ! grep -q "^$package$" "$REINSTALL_CONF";then echo "$package";fi;done
}

chen() {
check
enable && echo Enabled, will run on boot and self disable.
}
